/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_linjiamin_trace_ATraceRoute */

#ifndef _Included_com_linjiamin_trace_ATraceRoute
#define _Included_com_linjiamin_trace_ATraceRoute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_linjiamin_trace_ATraceRoute
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_linjiamin_trace_ATraceRoute_init
  (JNIEnv *, jobject);

/*
 * Class:     com_linjiamin_trace_ATraceRoute
 * Method:    start
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_linjiamin_trace_ATraceRoute_start
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_linjiamin_trace_ATraceRoute
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_linjiamin_trace_ATraceRoute_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
